max_device_count: 255
start_device_index: 0
log_level: 0
top_n: 3
cnn_type: "googlenet"
graph_file_path: "/opt/movidius/ncappzoo/caffe/GoogLeNet/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/imagenet1000.txt"
network_dimension: 224
channel1_mean: 104.0069879317889
channel2_mean: 116.66876761696767
channel3_mean: 122.6789143406786
scale: 1.0
