max_device_count: 255
start_device_index: 0
log_level: 0
top_n: 3
cnn_type: "inception_v1"
graph_file_path: "/opt/movidius/ncappzoo/tensorflow/inception_v1/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/imagenet1001.txt"
network_dimension: 224
channel1_mean: 128
channel2_mean: 128
channel3_mean: 128
scale: 0.0078125 
